# Generated by Django 3.1.4 on 2021-02-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courser_name',
            new_name='course_name',
        ),
        migrations.AlterField(
            model_name='course',
            name='courser_image',
            field=models.ImageField(upload_to='course.png'),
        ),
    ]
