# Generated by Django 3.1.4 on 2021-02-18 09:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210218_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='courser_image',
            field=models.ImageField(null=True, upload_to='course.png'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_premium',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='can_view',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.course'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='course_description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='course_module_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='video_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
