# Generated by Django 3.1.4 on 2021-02-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210218_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courser_image',
        ),
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
    ]
