# Generated by Django 3.1.4 on 2021-02-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pro_expiry_date',
            field=models.DateField(choices=[('Y', 'YEARLY'), ('F', 'FREE'), ('M', 'MONTHLY')], default='FREE', null=True),
        ),
    ]
