# Generated by Django 3.1.4 on 2021-02-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210220_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_type',
            field=models.CharField(choices=[('M', 'MONTHLY'), ('F', 'FREE'), ('Y', 'YEARLY')], default='FREE', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pro_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
