# Generated by Django 3.1.4 on 2021-02-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210220_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscription_type',
            field=models.CharField(choices=[('Y', 'YEARLY'), ('M', 'MONTHLY'), ('F', 'FREE')], default='FREE', max_length=100),
        ),
    ]
