# Generated by Django 3.1.4 on 2021-02-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210207_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
