# Generated by Django 3.1.4 on 2020-12-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(max_length=70, null=True),
        ),
    ]
