# Generated by Django 3.1.4 on 2021-01-23 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_many', '0002_posttwo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
